<?php

/**
 * @file
 * Functions to support theming in the DXPR Claro theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function dxpr_gin_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function dxpr_gin_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function dxpr_gin_preprocess_node(&$variables) {

}
