name: 'Image media type'
type: 'DXPR CMS'
description: 'Adds focal point-based cropping to the image media type.'
recipes:
  - core/recipes/image_media_type
install:
  - focal_point
  - key
  - ai
  - ai_provider_openai
  - ai_provider_anthropic
  - ai_image_alt_text
config:
  import:
    focal_point: '*'
    ai_image_alt_text: '*'
  actions:
    core.entity_form_display.media.image.media_library:
      setComponent:
        name: field_media_image
        options:
          type: image_focal_point
          weight: 1
          region: content
          settings:
            progress_indicator: throbber
            preview_image_style: media_library
            preview_link: true
            offsets: '50,50'
    ai_image_alt_text.settings:
      simple_config_update:
        autogenerate: true
        hide_button: true
    user.role.content_administrator:
      ensure_exists:
        id: content_administrator
        label: 'Content Administrator'
      grantPermission: 'generate ai alt tags'
    user.role.content_editor:
      ensure_exists:
        id: content_editor
        label: 'Content Editor'
      grantPermission: 'generate ai alt tags'
    user.role.marketer:
      ensure_exists:
        id: marketer
        label: 'Marketer'
      grantPermission: 'generate ai alt tags'
    user.role.site_bui:
      ensure_exists:
        id: site_bui
        label: 'Site Builder'
      grantPermission: 'generate ai alt tags'
