name: 'Blog'
type: 'DXPR CMS'
description: 'Sets up a basic blog, with tagging and commenting.'
recipes:
  - dxpr_cms_content_type_base
  - dxpr_cms_image
  - core/recipes/tags_taxonomy
  - dxpr_cms_dxpr_builder
install:
  - add_content_by_bundle
  - dxpr_builder_page
  - dxpr_theme_helper
  - menu_link_content
  - pathauto
  - shortcut
  - selective_better_exposed_filters
config:
  strict: false
  import:
    shortcut:
      - shortcut.set.default
    system:
      - system.menu.main
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'create blog content'
        - 'delete blog revisions'
        - 'delete any blog content'
        - 'edit any blog content'
