name: 'Accessibility tools'
type: 'DXPR CMS'
description: 'Installs and configures tools to help authors make their content accessible.'
install:
  - editoria11y
config:
  strict: false
  import:
    editoria11y: '*'
  actions:
    editoria11y.settings:
      simpleConfigUpdate:
        # Map tiles contain no alt text.
        # Skipping the map pane to limit reports
        # where the fix is outwith editors control.
        ignore_elements: '.leaflet-map-pane *'
