name: 'Image media type'
type: 'DXPR CMS'
description: 'Adds focal point-based cropping to the image media type.'
recipes:
  - core/recipes/image_media_type
install:
  - focal_point
  - responsive_image
  - svg_image
  - shortcut
  - key
  - ai
  - ai_provider_openai
  - ai_provider_anthropic
  - ai_image_alt_text
config:
  strict:
    - field.storage.media.field_media_svg_image
  import:
    focal_point: '*'
    ai_image_alt_text: '*'
    shortcut:
      - shortcut.set.default
  actions:
    core.entity_form_display.media.image.*:
      setComponent:
        name: field_media_image
        options:
          type: image_focal_point
          weight: 1
          region: content
          settings:
            progress_indicator: throbber
            preview_image_style: media_library
            preview_link: true
            offsets: '50,50'
      hideComponents:
        - uid
        - langcode
        - path
        - created
    # Disable the `files` view because it is not clear to most users what the
    # difference is between "Files" and "Media". We favor media.
    views.view.files:
      disable: {}
