name: 'Multilingual support'
type: 'DXPR CMS'
description: 'Adds support for translations.'
install:
  - config_translation
  - content_translation
  - block_content
  - hreflang
  - language
  - node
  - tmgmt
  - tmgmt_google
  - tmgmt_locale
  - tmgmt_content
  - tmgmt_config
  - user
config:
  import:
    language: '*'
    tmgmt: '*'
  actions:
    'language.content_settings.node.%bundle':
      createIfNotExistsForEachNodeType:
        target_entity_type_id: node
        target_bundle: '%bundle'
        language_alterable: true
    language.content_settings.node.*:
      setThirdPartySettings:
        - module: content_translation
          key: enabled
          value: true
        - module: content_translation
          key: bundle_settings
          value:
            untranslatable_fields_hide: '1'
    user.role.content_administrator:
      createIfNotExists:
        id: content_administrator
        label: Content Administrator
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
        label: Content editor
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.marketer:
      createIfNotExists:
        id: marketer
        label: Marketer
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'translate editable entities'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
    user.role.site_bui:
      createIfNotExists:
        id: site_bui
        label: Site Builder
      grantPermissions:
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'administer tmgmt'
        - 'accept translation jobs'
        - 'create translation jobs'
        - 'submit translation jobs'
        - 'translate any entity'
        - 'translate block_content'
        - 'translate editable entities'
        - 'translate interface'
        - 'translate menu_link_content'
        - 'translate tags taxonomy_term'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
