#!/usr/bin/env sh

## Description: Creates a new DXPR CMS recipe stub and adds it to the project.
## Usage: create-recipe NAME
## Example: "ddev create-recipe dxpr_cms_power_tools"

# Abort this script if any step of it fails.
set -e

# Ensure the recipe's directory exists with a basic `composer.json`.
if [ ! -d $1 ]; then
  mkdir $1 && cd $1
  composer init --no-interaction --name=drupal/$1 --type=drupal-recipe --require="drupal/core:>=10.3"
  composer config version dev-main
  cd ..
fi

# Add the recipe as a dependency of the main dxpr_cms recipe.
cd dxpr_cms_base
composer config repositories.$1 path ../$1
composer require --no-update "drupal/$1:*"
composer config --unset repositories
cd ..

# Ensure the recipe is defined as a path repository.
$HOME/bin/setup-repositories
