#!/usr/bin/env sh

## Description: Creates a new DXPR CMS recipe stub and adds it to the project.
## Usage: recipe-create NAME
## Example: "ddev recipe-create dxpr_cms_power_tools"
## Aliases: recipe:create,rc,create-recipe

# Abort this script if any step of it fails.
set -e

# Where the recipe will live.
DIR=recipes/$1

# Ensure the recipe's directory exists with a basic `composer.json`.
mkdir -p $DIR
composer init --working-dir=$DIR --no-interaction --name=drupal/$1 --description="" --require="drupal/core:>=10.3"
composer config version dev-main --working-dir=$DIR
composer config type drupal-recipe --working-dir=$DIR
composer config license GPL-2.0-or-later --working-dir=$DIR

# Create a license for the new recipe.
cp $DDEV_DOCROOT/core/LICENSE.txt $DIR

# Ensure the recipe is defined as a path repository.
composer config --file=components.composer.json repositories.$1 path $DIR
