name: dxpr-cms-dev
type: drupal
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
hooks:
  post-start:
    # Generate `composer.json` by merging the project template with our internal
    # dev requirements.
    - exec: 'jq -s ".[0] * .[1] * .[2]" project_template/composer.json dev.composer.json components.composer.json > composer.json'
    # Install all dependencies.
    - composer: 'install'
    # The installer is part of the project template, so symlink it into the web root.
    # It needs to be a relative symlink, or it will break Package Manager.
    - exec: 'ln -s -f $(realpath -s --relative-to=$DDEV_DOCROOT/profiles project_template/$DDEV_DOCROOT/profiles/dxpr_cms_installer) $DDEV_DOCROOT/profiles'
    # Install JavaScript dependencies if needed. The `--foreground-scripts`
    # option is needed to ensure the Cypress binary is actually downloaded;
    # see the warning about Node.js Snap for Linux at
    # https://docs.cypress.io/guides/getting-started/installing-cypress.
    - exec: 'test -d node_modules || npm clean-install --foreground-scripts'
web_environment:
  # For faster performance, don't audit dependencies automatically.
  - COMPOSER_NO_AUDIT=1
  # To display its UI, Cypress needs to be able to talk to an X11 server
  # running on the host machine.
  # - DISPLAY=host.docker.internal:0
  # Download Cypress to a directory that won't be blown away every time the
  # project is restarted.
  - CYPRESS_CACHE_FOLDER=/var/www/html/.cache/cypress
  # Use the DDEV-provided database to run PHPUnit tests.
  - SIMPLETEST_DB=$DDEV_DATABASE_FAMILY://db:db@db/db
  - SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL
webimage_extra_packages:
  # Add Cypress' system dependencies.
  # See https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - xauth
  - xvfb
  # Additional browsers for Cypress to test against.
  - chromium
  - firefox-esr
