name: Sync Current Branch and Tag

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:  # Adds manual trigger without inputs

jobs:
  sync:
    runs-on: ubuntu-24.04
    env:
      FORCE_PUSH: ${{ vars.FORCE_PUSH || 'false' }} # set to 'true' to enable force push
      TARGET_REPO_URL: ${{ vars.TARGET_REPO_URL || '' }} # set the target repo url, git protocol is supported, eg: git@git.drupal.org:project/dxpr_builder.git
      SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 || '' }}
      ALLOWED_BRANCHES_TO_SYNC: ${{ vars.ALLOWED_BRANCHES_TO_SYNC || '' }} # no branch to be synced by default
      ALLOWED_TAGS_TO_SYNC: ${{ vars.ALLOWED_TAGS_TO_SYNC || '' }} # no tag to be synced by default

# How to use:
# set env var of TARGET_REPO_URL (required) and optional: FORCE_PUSH, ALLOWED_BRANCHES_TO_SYNC env var
# must set secret key: SSH_PRIVATE_KEY_BASE64 for the sync to work, e.g: $ cat private_key_id_ed25519 | base64

    steps:

      - name: Check Target Repo URL and SSH Key
        id: check-config
        run: |

          if [  -z "${{ env.TARGET_REPO_URL }}" ]; then
            echo "Skipping the rest of the workflow as TARGET_REPO_URL is not set."
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ -z "${{ env.SSH_PRIVATE_KEY_BASE64 }}" ]; then
            echo "Error: SSH_PRIVATE_KEY_BASE64 is required when TARGET_REPO_URL is set."
            exit 1
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi


      - name: Checkout the Current Repository
        if: ${{ steps.check-config.outputs.skip == 'false' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        if: ${{ steps.check-config.outputs.skip == 'false' }}
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"

      - name: Decode and Set Up SSH Key
        if: ${{ steps.check-config.outputs.skip == 'false' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$(echo "${{ env.TARGET_REPO_URL }}" | awk -F'@' '{print $2}' | awk -F':' '{print $1}')" >> ~/.ssh/known_hosts

      - name: Extract Current Branch Name
        id: extract-branch
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            echo "Current branch name: $BRANCH_NAME"
            echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Extract Current Tag Name
        id: extract-tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "Current tag name: $TAG_NAME"
            echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Check if Branch is Allowed to Sync
        if: ${{ steps.extract-branch.outputs.branch != '' }}
        id: check-branch
        run: |
          BRANCH_NAME="${{ steps.extract-branch.outputs.branch }}"
          ALLOWED_BRANCHES="${{ env.ALLOWED_BRANCHES_TO_SYNC }}"
          
          echo "Current branch: $BRANCH_NAME"
          echo "Allowed branches: $ALLOWED_BRANCHES"
          
          if [[ ",$ALLOWED_BRANCHES," != *",$BRANCH_NAME,"* ]]; then
            echo "Branch '$BRANCH_NAME' is not in the allowed list for syncing."
            echo "skip_sync=true" >> $GITHUB_OUTPUT
          else
            echo "Branch '$BRANCH_NAME' is allowed for syncing."
            echo "skip_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync Branch to Target Repo
        if: ${{ steps.check-config.outputs.skip == 'false' && steps.check-branch.outputs.skip_sync == 'false' &&  steps.extract-branch.outputs.branch != '' }}
        run: |
          failed=false
          FORCE_PUSH=${{ env.FORCE_PUSH }}
          TARGET_REPO_URL=${{ env.TARGET_REPO_URL }}
          BRANCH_NAME="${{ steps.extract-branch.outputs.branch }}"  # The current branch name that triggered the push

          echo "Syncing branch: $BRANCH_NAME"

          # Ensure the branch is checked out
          git checkout "$BRANCH_NAME" || git checkout -b "$BRANCH_NAME" origin/"$BRANCH_NAME"

          # Attempt to push the branch
          if ! git push "$TARGET_REPO_URL" "$BRANCH_NAME"; then
            if [ "$FORCE_PUSH" == "true" ]; then
              echo "Force pushing branch: $BRANCH_NAME"
              if ! git push --force "$TARGET_REPO_URL" "$BRANCH_NAME"; then
                failed=true
              fi
            else
              failed=true
            fi
          fi

          if [ "$failed" = true ]; then
            echo "Error: Failed to push branch $BRANCH_NAME to the target repository"
            exit 1
          fi

      - name: Check if Tag is Allowed to Sync
        if: ${{ steps.extract-tag.outputs.tag != '' }}
        id: check-tag
        run: |
          TAG_NAME="${{ steps.extract-tag.outputs.tag }}"
          ALLOWED_TAGS="${{ env.ALLOWED_TAGS_TO_SYNC }}"
          
          echo "Current tag: $TAG_NAME"
          echo "Allowed tags: $ALLOWED_TAGS"
          
          if [[ ",$ALLOWED_TAGS," != *",$TAG_NAME,"* ]]; then
            echo "Tag '$TAG_NAME' is not in the allowed list for syncing."
            echo "skip_sync=true" >> $GITHUB_OUTPUT
          else
            echo "Tag '$TAG_NAME' is allowed for syncing."
            echo "skip_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync Tag to Target Repo
        if: ${{ steps.check-config.outputs.skip == 'false' && steps.check-tag.outputs.skip_sync == 'false' && steps.extract-tag.outputs.tag != '' }}
        run: |
          failed=false
          TARGET_REPO_URL=${{ env.TARGET_REPO_URL }}
          TAG_NAME="${{ steps.extract-tag.outputs.tag }}"  # The current tag name that triggered the push

          echo "Syncing tag: $TAG_NAME"
          git tag "$TAG_NAME" || echo "It's ok, tag $TAG_NAME already exists"
          # allow forge push?, currently, it's not allowed

          if ! git push "$TARGET_REPO_URL" "$TAG_NAME"; then
            failed=true
          fi

          if [ "$failed" = true ]; then
            echo "Error: Failed to push tag $TAG_NAME to the target repository"
            exit 1
          fi
